### Fetches all books
curl https://localhost:7002/books

### Fetches books by id
curl https://localhost:7002/books/id/1

### Fetches books by author
curl https://localhost:7002/books/author/Meredith Alonso

### Fetches books by title
curl https://localhost:7002/books/title/Learn Linq

### Create book
curl -X POST -H "Content-Type: application/json" -d '{"title":"The Art of Computer Programming","author":"Donald E. Knuth"}' https://localhost:7002/book

### Update Book
curl -X PUT -H "Content-Type: application/json" -d '{"id":"00000000-0000-0000-0000-000000000003","title":"Operating System Concepts","author":"Abraham Silberschatz"}' https://localhost:7002/book/00000000-0000-0000-0000-000000000003

### Delete Book
curl -X DELETE https://localhost:7002/book/00000000-0000-0000-0000-000000000001